# Generated by Django 5.2.4 on 2025-07-04 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nome_cliente', models.CharField(max_length=45)),
                ('email_cliente', models.EmailField(max_length=45, unique=True)),
                ('cpf_cliente', models.CharField(max_length=11, unique=True)),
                ('endereco_cliente', models.CharField(max_length=200)),
                ('telefone_cliente', models.CharField(max_length=45)),
            ],
        ),
    ]
