# Generated by Django 5.2.4 on 2025-07-04 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cliente', models.CharField(max_length=45)),
                ('email_cliente', models.EmailField(max_length=45, unique=True)),
                ('cpf_cliente', models.CharField(max_length=11, unique=True)),
                ('endereco_cliente', models.CharField(max_length=200)),
                ('telefone_cliente', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_funcionario', models.CharField(max_length=45)),
                ('cpf_funcionario', models.CharField(max_length=11, unique=True)),
                ('email_funcionario', models.EmailField(max_length=45, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Materia_Prima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_materia', models.CharField(max_length=45)),
                ('descricao_materia', models.CharField(max_length=150)),
                ('estoque_materia', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=45)),
                ('descricao_produto', models.CharField(max_length=150)),
                ('valor_produto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estoque_produto', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pedido', models.DateField()),
                ('valor_pedido', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status_pedido', models.CharField(max_length=20)),
                ('forma_pag_pedido', models.CharField(max_length=45)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='marcenaria.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Ordem_Producao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_produto', models.IntegerField()),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='marcenaria.funcionario')),
                ('materia_prima', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='marcenaria.materia_prima')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='marcenaria.produto')),
            ],
        ),
        migrations.CreateModel(
            name='Item_Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_item_pedido', models.IntegerField()),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='marcenaria.pedido')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='marcenaria.produto')),
            ],
        ),
        migrations.CreateModel(
            name='Produto_has_materia_prima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materia_prima', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='marcenaria.materia_prima')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='marcenaria.produto')),
            ],
        ),
    ]
