# Generated by Django 5.2.4 on 2025-07-04 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marcenaria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('data_pedido', models.DateField()),
                ('valor_pedido', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status_pedido', models.CharField(max_length=20)),
                ('forma_pag_pedido', models.CharField(max_length=45)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='marcenaria.cliente')),
            ],
        ),
    ]
