# Generated by Django 5.2.4 on 2025-07-04 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marcenaria', '0002_pedido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id_funcionario', models.AutoField(primary_key=True, serialize=False)),
                ('nome_funcionario', models.CharField(max_length=45)),
                ('cpf_funcionario', models.CharField(max_length=11, unique=True)),
                ('email_funcionario', models.EmailField(max_length=45, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Materia_Prima',
            fields=[
                ('id_materia', models.AutoField(primary_key=True, serialize=False)),
                ('nome_materia', models.CharField(max_length=45)),
                ('descricao_materia', models.CharField(max_length=150)),
                ('estoque_materia', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id_produto', models.AutoField(primary_key=True, serialize=False)),
                ('nome_produto', models.CharField(max_length=45)),
                ('descricao_produto', models.CharField(max_length=150)),
                ('valor_produto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estoque_produto', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ordem_Producao',
            fields=[
                ('id_ordem_producao', models.AutoField(primary_key=True, serialize=False)),
                ('quantidade_produto', models.IntegerField()),
                ('funcionario_id_funcionario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='marcenaria.funcionario')),
                ('materia_prima_id_materia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='marcenaria.materia_prima')),
                ('produto_id_produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='marcenaria.produto')),
            ],
        ),
        migrations.CreateModel(
            name='Item_Pedido',
            fields=[
                ('id_item_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('quantidade_item_pedido', models.IntegerField()),
                ('pedido_id_pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='marcenaria.pedido')),
                ('produto_id_produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='marcenaria.produto')),
            ],
        ),
        migrations.CreateModel(
            name='Produto_has_materia_prima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materia_prima_id_materia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='marcenaria.materia_prima')),
                ('produto_id_produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='marcenaria.produto')),
            ],
        ),
    ]
